services:
  bot:
    build: .
    container_name: team_project
    stop_grace_period: 40s
    depends_on:
      db:
        condition: service_healthy
  db:
    build: deploy/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=teamproject
    healthcheck:
      test: pg_isready --dbname=teamproject --host=127.0.0.1 --username=postgres
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: team_project_db
    volumes:
      - postgresql:/var/lib/postgresql
    expose:
      - "5432"
volumes:
  postgresql: